# General
RESERVATION_MAX_HOURS = 0.0083

# VSYS Max by model
PA1410_MAX_VSYS = 5 # default vsys plus 4

# Max days a reservation is valid
RESERVATION_MAX_DAYS = 2

# Prefix for vsys resrevation name
RESERVATION_PREFIX = "RES-"

# Logging setup
LOG_LEVEL = "INFO"
LOG_FILE = "vsys_dashboard.log"
LOG_DIR = "logs/"