# General
RESERVATION_MAX_HOURS = 0.0083
DB_PATH = "db/zone_data.json"

# VSYS Max by model
PA1410_MAX_VSYS = 5 # default vsys plus 4

# Max days a reservation is valid
RESERVATION_MAX_DAYS = 2

# Prefix for vsys resrevation name
RESERVATION_PREFIX = "RES-"

# Panorama details
PANORAMA = "204.232.167.99"
# Oauth provider URL
AUTHORITY_URL = "https://login.microsoftonline.com/"
REDIRECT_URI = "http://localhost:8505"
# Logging setup
LOG_LEVEL = "INFO"
LOG_FILE = "vsys_dashboard.log"
LOG_DIR = "logs/"

# Device Group List Scope
DEVICE_GRPS = ["GTS-VSYS-ORD", "GTS-VSYS-DFW", "GTS-VSYS-IAD", "GTS-VSYS-FRA", "GTS-VSYS-HKG", "GTS-VSYS-LON", "GTS-VSYS-SIN", "GTS-VSYS-SJC", "GTS-VSYS-SYD"]

# Facts details
FACTS_TOKEN_URL = "https://identity-internal.api.rackspacecloud.com/v2.0/tokens"
FACTS_URL = "https://facts.nsi.rackspace.com/vsys_infra/vsys_infra"
PER_PAGE = 50
 

